#! /bin/sh
# https://github.com/dryobates/tcr

# set -o pipefail  # bash
set -eu
TEST_PREFIX="T"
BEHAVIOUR_PREFIX="B"
STRUCTURE_PREFIX="S"
DEFAULT_MESSAGE="working"

main() {
    if [ $# = "0" ];
    then
        usage
    fi
    expected=${1:-}
    shift
    check_guards
    case $expected in
        red)
            set_test_commit_message $*
            test && revert || commit "$message"
            ;;
        green)
            set_behaviour_or_structure_commit_message $*
            test && commit "$message" || revert
            ;;
        *)
            usage
            ;;
    esac
}


usage() {
    error "Usage: tcr {red,green} [msg]"
}

check_guards() {
    error_when_not_git_repository
    error_when_no_initial_commit
}

error_when_not_git_repository() {
    find_repo $PWD || error "Run from git repository!"
}

find_repo() {
    path=`realpath $1`
    if [ ! -d $path/.git ];
    then
        if [ "$path" != "/" ];
        then
            find_repo $path/..
        else
            false
        fi
    fi
}

error_when_no_initial_commit() {
    git show > /dev/null 2>&1 || error "At least initial commit is needed"
}

error() {
    echo $1
    exit 1
}

set_test_commit_message() {
    set_test_commit_message_prefix
    message=${*:-$DEFAULT_MESSAGE}
    message="$prefix $message"
}

set_test_commit_message_prefix() {
    prefix=$TEST_PREFIX
}

set_behaviour_or_structure_commit_message() {
    set_behaviour_or_structure_commit_message_prefix
    message=${*:-}
    if [ -z "$message" ];
    then
        any_prefix="\(${TEST_PREFIX}\|${BEHAVIOUR_PREFIX}\|${STRUCTURE_PREFIX}\)"
        message=`git show -s --format='format:%s' | sed -e "s/^$any_prefix //"`
    fi
    message="$prefix $message"
}

set_behaviour_or_structure_commit_message_prefix() {
    B_or_S_prefix="\(${BEHAVIOUR_PREFIX}\|${STRUCTURE_PREFIX}\)"
    last_prefix_is_B_or_S=`git show -s --format='format:%s' | grep -o "^${B_or_S_prefix}" || true`
    if [ -z $last_prefix_is_B_or_S ];
    then
        prefix=$BEHAVIOUR_PREFIX
    else
        prefix=$STRUCTURE_PREFIX
    fi
}

test() {
    ${TCR_TEST_COMMAND:-make test}
}

commit() {
    message=${1:-}
    git commit -am "$message"
}

revert() {
    git stash
    exit 1
}

[ "run" = "${TCR_TESTING:-run}" ] && main $* || true
