#! /bin/sh
# https://github.com/dryobates/tcr

set -euo pipefail

main() {
    expected=${1:-}
    case $expected in
        red)
            check_guards
            $TCR_TEST_COMMAND && revert || commit
            ;;
        green)
            check_guards
            $TCR_TEST_COMMAND || revert && commit
            ;;
        *)
            error "Usage: tcr {red,green} [msg]"
            ;;
    esac
}

check_guards() {
    error_when_not_git_repository
    error_when_no_initial_commit
}

error_when_not_git_repository() {
    test -d .git || error "Run from git repository!"
}

error_when_no_initial_commit() {
    git show > /dev/null 2>&1 || error "At least initial commit is needed"
}

error() {
    echo $1
    exit 1
}

revert() {
    git stash
    exit 1
}

commit() {
    git commit -am "working"
}

main $*
