#! /bin/sh
# https://github.com/dryobates/tcr

set -euo pipefail
TEST_PREFIX="T"
BEHAVIOUR_PREFIX="B"
STRUCTURE_PREFIX="S"

main() {
    if [ $# == "0" ];
    then
        usage
    fi
    expected=${1:-}
    shift
    message=${*:-working}
    case $expected in
        red)
            check_guards
            test && revert || commit "$TEST_PREFIX $message"
            ;;
        green)
            check_guards
            set_behaviour_or_structure_prefix
            test && commit "$prefix working" || revert
            ;;
        *)
            usage
            ;;
    esac
}

usage() {
    error "Usage: tcr {red,green} [msg]"
}

check_guards() {
    error_when_not_git_repository
    error_when_no_initial_commit
}

error_when_not_git_repository() {
    [ -d .git ] || error "Run from git repository!"
}

error_when_no_initial_commit() {
    git show > /dev/null 2>&1 || error "At least initial commit is needed"
}

error() {
    echo $1
    exit 1
}

test() {
    $TCR_TEST_COMMAND
}

set_behaviour_or_structure_prefix() {
    last_prefix_is_B_or_S=`git show -s --format='format:%s' | grep -o "^\(${BEHAVIOUR_PREFIX}\|${STRUCTURE_PREFIX}\)" || true`
    if [ -z $last_prefix_is_B_or_S ];
    then
        prefix=$BEHAVIOUR_PREFIX
    else
        prefix=$STRUCTURE_PREFIX
    fi
}


commit() {
    message=${1:-}
    git commit -am "$message"
}

revert() {
    git stash
    exit 1
}

main $*
